### ISSUE TITLE
Flow

### ISSUE THREAD

**Issue by ca-lida** [ca-lida/what-could-go-wrong-peer-production#3]

**Comment by Naopod** [comment]
What about adding a time limit for discussions ?

**Comment by vallathortense** [comment]
> What about adding a time limit for discussions ?

mmmm yeah good idea ! what about 10 min ? We stilll need to have time to debate otherwise the game is useless ?

**Comment by Naopod** [comment]
> > What about adding a time limit for discussions ?
> 
> mmmm yeah good idea ! what about 10 min ? We stilll need to have time to debate otherwise the game is useless ?

Yep, 10 minutes seems fine, it allows users to be clear yet debate

**Comment by Matthieu-z-David** [comment]
I saw some PR from group members also adding rules regarding time, implementing more flexibility.
Overall this topic has been implemented in past PR. This is settled.

**Comment by Matthieu-z-David** [comment]
I saw some PR from group members also adding rules regarding time, implementing more flexibility.
Overall this topic has been implemented in past PR. This is settled.
